<?php
/*
   PHP DEVELOPED BY: FAILBR34K
   MODIFIED BY: BRAYAN VILLA
*/
//=======================================================================================================================================//

$activation= (array_key_exists('activation-info-base64', $_POST)
                          ? base64_decode($_POST['activation-info-base64'])
                          : array_key_exists('activation-info', $_POST) ? $_POST['activation-info'] : '');
						  
if(!isset($activation) || empty($activation))
{
	header('location: https://LOCALIZACIÓN DE PAGINA DE ERROR DE SU SERVIDOR/404.html'); 
	exit('404'); 
}
//=======================================================================================================================================//

//Load & Decode ActivationInfoXML
//Carga y decodificación de ActivationInfoXML

$encodedrequest = new DOMDocument;
$encodedrequest->loadXML($activation);
$activationDecoded= base64_decode($encodedrequest->getElementsByTagName('data')->item(0)->nodeValue);

$decodedrequest = new DOMDocument;
$decodedrequest->loadXML($activationDecoded);
$nodes = $decodedrequest->getElementsByTagName('dict')->item(0)->getElementsByTagName('*');

//=======================================================================================================================================//

for ($i = 0; $i < $nodes->length - 1; $i=$i+2)
{
   switch ($nodes->item($i)->nodeValue) 
   {
      case "ActivationRandomness": $activationRandomness = $nodes->item($i + 1)->nodeValue; break;
      case "ActivationState": $activationState = $nodes->item($i + 1)->nodeValue; break;
      case "BasebandSerialNumber": $baseSerial = $nodes->item($i + 1)->nodeValue; break;
      case "DeviceCertRequest": $deviceCertRequestBase64 = base64_decode($nodes->item($i + 1)->nodeValue); break;
      case "DeviceClass": $deviceType = $nodes->item($i + 1)->nodeValue; break;
      case "InternationalMobileEquipmentIdentity": $imei = $nodes->item($i + 1)->nodeValue; break;
      case "InternationalMobileSubscriberIdentity": $imsi = $nodes->item($i + 1)->nodeValue; break;
      case "IntegratedCircuitCardIdentity": $iccid = $nodes->item($i + 1)->nodeValue; break;
      case "MobileEquipmentIdentifier": $meid = $nodes->item($i + 1)->nodeValue; break;
      case "ProductType": $ProductType = $nodes->item($i + 1)->nodeValue; break;
      case "ProductVersion": $productVersion = $nodes->item($i + 1)->nodeValue; break;
      case "UniqueDeviceID": $uniqueDiviceID = $nodes->item($i + 1)->nodeValue; break;
      case "UniqueChipID": $ucid = $nodes->item($i + 1)->nodeValue; break;
      case "SerialNumber": $serial = $nodes->item($i + 1)->nodeValue; break;
    }
}

//=======================================================================================================================================//

$folder =  'Activate/Devices/'.$deviceType.'/'.$ProductType.'/';
if(!file_exists ($folder))
{
	mkdir ($folder, 00777, true);
}
else
{
	
}

//=======================================================================================================================================//
// This is a device activation information without linking to Find My iPhone, so Albert responds with an ActivationRecord

// Esta es una información de activación de un dispositivo sin vinculación a Buscar mi iPhone, por lo que albert responde con un ActivationRecord

$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL => "https://albert.apple.com/deviceservices/deviceActivation",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS => array('InStoreActivation' => 'false','AppleSerialNumber' => 'F4GTGYJZHG7F','IMEI' => '355324087826421','MEID' => '','IMSI' => '655012840853271','ICCID' => '89284000000008532719','activation-info' => '<dict>
    <key>ActivationInfoComplete</key>
	<true/>
	<key>ActivationInfoXML</key>
	<data>
	PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBs
	aXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3
	dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJz
	aW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+QWN0aXZhdGlvblJlcXVlc3RJbmZvPC9rZXk+
	Cgk8ZGljdD4KCQk8a2V5PkFjdGl2YXRpb25SYW5kb21uZXNzPC9rZXk+CgkJPHN0cmlu
	Zz4yRTlERUFFNi1EOUE0LTQ5OTYtQTI5QS01Njk2NjhBRTJFMTQ8L3N0cmluZz4KCQk8
	a2V5PkFjdGl2YXRpb25TdGF0ZTwva2V5PgoJCTxzdHJpbmc+VW5hY3RpdmF0ZWQ8L3N0
	cmluZz4KCQk8a2V5PkZNaVBBY2NvdW50RXhpc3RzPC9rZXk+CgkJPHRydWUvPgoJPC9k
	aWN0PgoJPGtleT5CYXNlYmFuZFJlcXVlc3RJbmZvPC9rZXk+Cgk8ZGljdD4KCQk8a2V5
	PkFjdGl2YXRpb25SZXF1aXJlc0FjdGl2YXRpb25UaWNrZXQ8L2tleT4KCQk8dHJ1ZS8+
	CgkJPGtleT5CYXNlYmFuZEFjdGl2YXRpb25UaWNrZXRWZXJzaW9uPC9rZXk+CgkJPHN0
	cmluZz5WMjwvc3RyaW5nPgoJCTxrZXk+QmFzZWJhbmRDaGlwSUQ8L2tleT4KCQk8aW50
	ZWdlcj45NjwvaW50ZWdlcj4KCQk8a2V5PkJhc2ViYW5kTWFzdGVyS2V5SGFzaDwva2V5
	PgoJCTxzdHJpbmc+OENCMTVFRTRDODAwMjE5OTA3MEQ5NTAwQkI4RkIxODNCMDI3MTNB
	NUNBMkE2QjkyREI1RTc1Q0UxNTUzNjE4Mjwvc3RyaW5nPgoJCTxrZXk+QmFzZWJhbmRT
	ZXJpYWxOdW1iZXI8L2tleT4KCQk8ZGF0YT4KCQlrMEVBNlRFQXRQTjRFMXVtCgkJPC9k
	YXRhPgoJCTxrZXk+R0lEMTwva2V5PgoJCTxzdHJpbmc+ZmY8L3N0cmluZz4KCQk8a2V5
	PkdJRDI8L2tleT4KCQk8c3RyaW5nPmZmPC9zdHJpbmc+CgkJPGtleT5JbnRlZ3JhdGVk
	Q2lyY3VpdENhcmRJZGVudGl0eTwva2V5PgoJCTxzdHJpbmc+ODkyODQwMDAwMDAwMDg1
	MzI3MTk8L3N0cmluZz4KCQk8a2V5PkludGVybmF0aW9uYWxNb2JpbGVFcXVpcG1lbnRJ
	ZGVudGl0eTwva2V5PgoJCTxzdHJpbmc+MzU1MzI0MDg3ODI2NDIxPC9zdHJpbmc+CgkJ
	PGtleT5JbnRlcm5hdGlvbmFsTW9iaWxlU3Vic2NyaWJlcklkZW50aXR5PC9rZXk+CgkJ
	PHN0cmluZz42NTUwMTI4NDA4NTMyNzE8L3N0cmluZz4KCQk8a2V5PkludGVybmF0aW9u
	YWxNb2JpbGVTdWJzY3JpYmVySWRlbnRpdHlPdmVycmlkZTwva2V5PgoJCTxmYWxzZS8+
	CgkJPGtleT5QUklWZXJzaW9uX01ham9yPC9rZXk+CgkJPGludGVnZXI+MDwvaW50ZWdl
	cj4KCQk8a2V5PlBSSVZlcnNpb25fTWlub3I8L2tleT4KCQk8aW50ZWdlcj4wPC9pbnRl
	Z2VyPgoJCTxrZXk+UFJJVmVyc2lvbl9SZWxlYXNlTm88L2tleT4KCQk8aW50ZWdlcj4x
	PC9pbnRlZ2VyPgoJCTxrZXk+UGhvbmVOdW1iZXI8L2tleT4KCQk8c3RyaW5nPisyNzcx
	MjQ0MDY5Nzwvc3RyaW5nPgoJCTxrZXk+U0lNR0lEMTwva2V5PgoJCTxkYXRhPgoJCS93
	PT0KCQk8L2RhdGE+CgkJPGtleT5TSU1HSUQyPC9rZXk+CgkJPGRhdGE+CgkJL3c9PQoJ
	CTwvZGF0YT4KCQk8a2V5PlNJTVN0YXR1czwva2V5PgoJCTxzdHJpbmc+a0NUU0lNU3Vw
	cG9ydFNJTVN0YXR1c1JlYWR5PC9zdHJpbmc+CgkJPGtleT5TdXBwb3J0c1Bvc3Rwb25l
	bWVudDwva2V5PgoJCTx0cnVlLz4KCQk8a2V5PmtDVFBvc3Rwb25lbWVudEluZm9QUklW
	ZXJzaW9uPC9rZXk+CgkJPHN0cmluZz4wLjAuMTwvc3RyaW5nPgoJCTxrZXk+a0NUUG9z
	dHBvbmVtZW50SW5mb1NlcnZpY2VQcm92aXNpb25pbmdTdGF0ZTwva2V5PgoJCTx0cnVl
	Lz4KCTwvZGljdD4KCTxrZXk+RGV2aWNlQ2VydFJlcXVlc3Q8L2tleT4KCTxkYXRhPgoJ
	TFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTQlNSVkZWUlZOVUxTMHRMUzBLVFVs
	SlFuaEVRME5CVXpCRFFWRkIKCWQyZFpUWGhNVkVGeVFtZE9Wa0pCVFZSS1JHc3pUMVZP
	UTA1RldUVk1WVmt3VDFSQmRFNUZSVFJPYVRBMVVsVlJOUTBLCglURlZhUkUxRlNrZE9h
	MWt6VG10UmQxRjZSVXhOUVd0SFFURlZSVUpvVFVOV1ZrMTRRM3BCU2tKblRsWkNRV2RV
	UVd0TwoJUWsxU1NYZEZRVmxFVmxGUlNBMEtSWGRzUkdSWVFteGpibEp3WW0wNGVFVjZR
	VkpDWjA1V1FrRnZWRU5yUm5kalIzaHMKCVNVVnNkVmw1TkhoRWVrRk9RbWRPVmtKQmMx
	UkNiV3hSWVVjNWRRMEtXbFJEUW01NlFVNUNaMnR4YUd0cFJ6bDNNRUpCCglVVVZHUVVG
	UFFtcFJRWGRuV1d0RFoxbEZRVzB3TkdwMGVXVTFXRmRpY2xnNVNHVklTU3RhYWtGd1RB
	MEtaMWxDY25CaQoJUkdkVFpVNDRNM05JTVVwVGMwaFRRbXhhYWpOQ1oxVkVZMDFVUWxw
	emFrVklZbmhsUzBOWWVWbGhPVzlPWWpSdVkxTTQKCVZuSkxTaXNyYVEwS01teFRSMDFK
	ZFZwelNpOW5VMUpGWkVoQ1FtaFJOMVZVTW1wVVVuTTFURTFXVEcwcmRHTmxTVWhJCgll
	V2RTTTFCcmFUWkNhblpXVGxnM05UaEVSa28xWXcwS1RteHJlbG96Y2xBME0wbDFlRE40
	WkdscU9FTkJkMFZCUVdGQgoJUVUxQk1FZERVM0ZIVTBsaU0wUlJSVUpDVVZWQlFUUkhR
	a0ZLUlZnMlFuQkZkM2hOUlEwS1ZGSkJNbFpIVlVOT2RUbHkKCU9VOXpjbFZGUVM5MVR6
	RmtlSFJNUzNWVE1IaDNURGxPUjB4U1JIVnFNV05xUlZKNFdYRndjR2hyTW0xeVRUZGFO
	VlZMCglRZzBLVG1kc1ZHNTFMMFYxYTJac1VUZERXSEEzT0RsUk5sUjViRGxpTW1NMGRE
	ZFZhamhOYUdwUlpEZFVkVFUxUzNwcQoJU1ZKMFlubHJhV0ptWlRWYWVqaFdTZzBLYzBO
	SGMyczBlRlZNUmpRd2FEQlROamRKUmpsdFducFBSMjFoTDBwWFNuQUsKCUxTMHRMUzFG
	VGtRZ1EwVlNWRWxHU1VOQlZFVWdVa1ZSVlVWVFZDMHRMUzB0Cgk8L2RhdGE+Cgk8a2V5
	PkRldmljZUlEPC9rZXk+Cgk8ZGljdD4KCQk8a2V5PlNlcmlhbE51bWJlcjwva2V5PgoJ
	CTxzdHJpbmc+RjRHVEdZSlpIRzdGPC9zdHJpbmc+CgkJPGtleT5VbmlxdWVEZXZpY2VJ
	RDwva2V5PgoJCTxzdHJpbmc+MGE0NjMwNWNhMmVjODBmOTdmMjhhMjJiN2I5NzdjNDVh
	MDFjODI4YTwvc3RyaW5nPgoJPC9kaWN0PgoJPGtleT5EZXZpY2VJbmZvPC9rZXk+Cgk8
	ZGljdD4KCQk8a2V5PkJ1aWxkVmVyc2lvbjwva2V5PgoJCTxzdHJpbmc+MTlIMzA3PC9z
	dHJpbmc+CgkJPGtleT5EZXZpY2VDbGFzczwva2V5PgoJCTxzdHJpbmc+aVBob25lPC9z
	dHJpbmc+CgkJPGtleT5EZXZpY2VWYXJpYW50PC9rZXk+CgkJPHN0cmluZz5BPC9zdHJp
	bmc+CgkJPGtleT5Nb2RlbE51bWJlcjwva2V5PgoJCTxzdHJpbmc+TU44WDI8L3N0cmlu
	Zz4KCQk8a2V5Pk9TVHlwZTwva2V5PgoJCTxzdHJpbmc+aVBob25lIE9TPC9zdHJpbmc+
	CgkJPGtleT5Qcm9kdWN0VHlwZTwva2V5PgoJCTxzdHJpbmc+aVBob25lOSwzPC9zdHJp
	bmc+CgkJPGtleT5Qcm9kdWN0VmVyc2lvbjwva2V5PgoJCTxzdHJpbmc+MTUuNy4zPC9z
	dHJpbmc+CgkJPGtleT5SZWdpb25Db2RlPC9rZXk+CgkJPHN0cmluZz5BQTwvc3RyaW5n
	PgoJCTxrZXk+UmVnaW9uSW5mbzwva2V5PgoJCTxzdHJpbmc+QUEvQTwvc3RyaW5nPgoJ
	CTxrZXk+UmVndWxhdG9yeU1vZGVsTnVtYmVyPC9rZXk+CgkJPHN0cmluZz5BMTc3ODwv
	c3RyaW5nPgoJCTxrZXk+U2lnbmluZ0Z1c2U8L2tleT4KCQk8dHJ1ZS8+CgkJPGtleT5V
	bmlxdWVDaGlwSUQ8L2tleT4KCQk8aW50ZWdlcj42ODM2NjQzMDQ5MzkwODg2PC9pbnRl
	Z2VyPgoJPC9kaWN0PgoJPGtleT5SZWd1bGF0b3J5SW1hZ2VzPC9rZXk+Cgk8ZGljdD4K
	CQk8a2V5PkRldmljZVZhcmlhbnQ8L2tleT4KCQk8c3RyaW5nPkE8L3N0cmluZz4KCTwv
	ZGljdD4KCTxrZXk+U29mdHdhcmVVcGRhdGVSZXF1ZXN0SW5mbzwva2V5PgoJPGRpY3Q+
	CgkJPGtleT5FbmFibGVkPC9rZXk+CgkJPHRydWUvPgoJPC9kaWN0PgoJPGtleT5VSUtD
	ZXJ0aWZpY2F0aW9uPC9rZXk+Cgk8ZGljdD4KCQk8a2V5PkJsdWV0b290aEFkZHJlc3M8
	L2tleT4KCQk8c3RyaW5nPmMwOmQwOjEyOmI1OjJiOjg3PC9zdHJpbmc+CgkJPGtleT5C
	b2FyZElkPC9rZXk+CgkJPGludGVnZXI+MTI8L2ludGVnZXI+CgkJPGtleT5DaGlwSUQ8
	L2tleT4KCQk8aW50ZWdlcj4zMjc4NDwvaW50ZWdlcj4KCQk8a2V5PkV0aGVybmV0TWFj
	QWRkcmVzczwva2V5PgoJCTxzdHJpbmc+YzA6ZDA6MTI6YjU6MmI6ODg8L3N0cmluZz4K
	CQk8a2V5PlVJS0NlcnRpZmljYXRpb248L2tleT4KCQk8ZGF0YT4KCQlNSUlYRkFJQkFq
	Q0NGdzBFSVA0QzNzcVF0UDFTMmh3Qlp6Q29IY3NvSDJ4TnU1YythNFE0NW9KMU1LRjMK
	CQlCRUVFa0hVOUJVNW45a2xuZktSUmUyaElpQXg2VjZOdmNzWWF0M1M4T0NHeWcxM2Js
	UndGaHE4dnVGSjkKCQlabmt6NkVnMFRYck1FbmdzMWo5ZGxTOVlVZGlsM2dRUW9TenR3
	aW92ajBCU1F6bTFwLzQyMUFRUVFRK0wKCQloWUUrY0ZrQzQ4eG4zd2JXK0FTQ0ZvQ0tt
	bXNSd1FHRUU5MnEzVjJYUDNjN3F5VllWN1JsK1d4OS94Q1AKCQkwQkdjZU9XT1lIR3ZK
	dkVxN29ZSHFtWkVZa2lLVGFMRXN6VWpYSXhrSTlWZGdqUW1wdDRScWVzclpFc2YKCQlI
	OEtBWDRKWGpKOG1PeFVXc2Q3ZC9RU3RBVFZBV3NUTWdJVC9yZXVoOUFCMVRWUmN1QmRQ
	OUdNTW44d1kKCQkvNzVkcVg2S2kzb09ZQ3poVzdhUm9OdlBGVVZML0xtSjBsdG9NZkg0
	a0xZeFZ4Wm9xa1hZMFZLVmUxTDAKCQlJZ3B2YU5ZOFB6UkhZSWpKT1BVMDQ3QW9odmVN
	MHNjVmtqd2U4bW5FK0FteTY1USt3a3M3cm5ieTlhRTIKCQlQdjlUK3BOUUtZbDRJU0xZ
	em44YzIySXlkbkNEWHByZHM0b0lPMGk1aENjeVZWSTJBcU5ZR3gwd1BVZmEKCQlpSHpC
	SXArRlNJT1BiNUgyWTcvU3FUK3dtQTFoTE5xYnJNWjQ5VU9XaWVyMnZiR1hKMld4bHVs
	OU1mVG8KCQk0T3lJTUpIYWtVWmpvWU14cXZPQ1lyNEUzWDY2QVJoTUFMQ0ZNYk13TTFE
	MCs4VW5PK3p1Y2hPY2NuL3YKCQlzZGU5Q2NHTVBUSFpKZW9HQTdBNENjQlBySTNWTWNy
	QTZsR3JDRzdMcERSSjlqZ0JNdk5WUTNWQkI1S0cKCQlTRVU4WUlRUndHSHFHWStNODNk
	bkU3MDFHamh2eXdxZmhMbUsyOHZFZDBXRFZhdXBKbHdzaEx2L0VDZVkKCQlCQ3NnbXk2
	akw0d0RmN2Q4UXdOUW5sNlNkTlMwRkhJOENvUVUxTU5HK0lKSmpkdjY3Y2phZDlha3Z0
	bW0KCQk3VVZ6Vlo5d0tOYmVzNHRQaGZUK2R0SUhLNGZYVCtUczZ0dWhQRjBlZkhHcHpO
	R2Q4d1VXdGF1V0RORkEKCQlQTndRaWJ3RU9pMEVjZGo1K09EUXZlMm1KNVN4ZVg1ZDRx
	dXM5Y2hmOTZXWEt4UUp1c2FCVHRMSlVyNCsKCQlBbDY5NzM0bE41NncvRTZxMlozQU5k
	TlRMRUhNQ29WTmdFMlFMSzVtN3BGNS9TeG9BRVZEN0xWTVBMMS8KCQkvK0xTdXppSTBw
	OXdESFZPbmkvSnRCREg2dWVHQnpITlp1c0VCWk0zNHZoaERKV2xvUVJtSCtJN1ZCNXYK
	CQlMZERneUUxK2Ntc1BUR0o1Q1BtVFRQSlBBR0pnQWFBV0lLOTdhVXFtQWVvUWJyKy9T
	emZtOXFleTN1TCsKCQlZMzlJb2wxbi9BblBRM2kwSkE1SVlXVUFKb3F4UThQODJlSXJO
	cWVvWXRab3Z2eUJmbGsxSk4vNlQ5RHgKCQlzQ1lOeExORW0wU1RVMW9yNnJ4VElnbkZo
	aGIzSXFYa2hZNXFBekM1Q3NYUWpmUTduZzJJSTdzYy9kSHEKCQlLYndoOEdNekZtWGNM
	MzliZThtL0RxcGdjOVRrUHNTWVczcDdTQXc5ODUvS3BlNWU4YTZ4MUNScUE2d1MKCQlU
	WXMwZlZ4UVA4NkhtYXh3OWo5Z3ZrcmhtY2VleTZRQWtMak81ZWhrY0l3REsrOWk5SGtD
	Q0lDZm1ORE4KCQlBVnRCMWJad25JYVVOais4NEZyWURBcTAzdHNKQmxLYVNzdzM0MFdJ
	YnlSZm5kV2lDVWQ4NGE4VjM2TWQKCQlPbG1XTnNVNGI3eTV0NzZHOXpscGs0QWwzajAz
	a3VnbGh2cjNnRGFxWjU1TWpEeThFcktiV2ZhSDVDQjcKCQlTNHMxMnFWREc1dDdWeGg5
	ZUZKald5dVFsSUdnKzVWNmVYc01Lcko2UjJ0Q2RWVWVTZTA4dXVOcmEzcmkKCQlyWGNM
	bHNQcmtJM2x6QjlRUER1SXkyZGtSSy94OWJOdTYxUWFQNWdDdlhnT0hjcjByS21CWVN5
	YW83WjMKCQlsTWtNSXRSSG9BMWIzTnJUZUxkQ1YxS1FhZTQxNmNnalNGcU16SCswK0hF
	bTdvV2Y1U3hVZDRWaFFmYzMKCQk0VzhZUGdGVFVmOGQzdkZvR2liVkxobm1pQVJiRjNW
	SlJaYmxqaEE2NFZMV3JYTTV6b2NoS1BFb1lSUEkKCQlSaGdNZ2dRYkRZTnBVS2RVUTIy
	OHRKeUgxWm5rKzUxNUNwVW1pRFJkUW45SGNuV3F5QzROSmFha2dPUmkKCQlNNmxoNkhJ
	VFhCb3JsazFSYStGZHpRSTgxU0Y4RlBJT2NrN1hiMkNISEhjam9EL2tmRWlieEw5cE9V
	c3UKCQljWHJSOXU2OGFBakUvVjl3MkdBUmN5MmVucWx3L3FDcUNpOUd1U1ZzNlZ0Szhs
	cnlXc3R4N2JPOFI0c0sKCQlJcDc1Q2FuZkJCeGNKSzkzN1h6dXFNN1hEbzRZM25JU0hh
	emEwK2c4cFJFeXJIV25mMW9yU2hhR2lXcGQKCQk1azUrU2g1L1MyVUFpR3VGc2pBbGhT
	SGdWRnRhNmpFVW9hV2MzNTJqeU0vSkVrZ2o1TWhUbUk2RkJ5bHcKCQl1WmtjTERLR2pI
	K0RITGs4Qm0vb09XRjU3SzlRUHhaeEh2RzRpSHYwbmpuRXZDdlpVckV1K2dhdlRIeFEK
	CQlaY0QxdW1xMkRMVW5rRzZlTVp2aU1xK3NYUW9yeHVodjZQWGgvdWVTQmt1cU9xQURL
	cmhoSFpQSmFJeWMKCQlWRWNXY3hZS3hJT3VyRlBITkUyaWhaQUpIQXdpdHVxOWhnL0hz
	TGliMERGMVk0YVQzV1hUc3FCZHFVUEsKCQk1VmJ2ekR0SjBicjNBVGlpNDM2bFIwM3h3
	OGR4Y2FseXRHa0gwaEZLTzZYcXNZaTN2SlNGYUt2OXE4d2IKCQlpUk50WjgwUVBjanpH
	OWc1QUIycjlhcE41OU1nR0JaL21iRHg5ZXpTeVMxczExNVNXeVNRUFpNMmZRY0cKCQlC
	VEhmZkVSNGJMNThoOEZxMVJtOVRFTXhDa0owUlNOc0ZqcFZIOVdYUXZQcWNKWDdzVVA2
	K2pNNzcvN24KCQlCVUQ1UjA3cTdMNzZGNnhQL1p5Z2ZRYmhjblN5ZElrVFFCYU1HdWpr
	Q2pkUHEvYVc1Z2RFTmkwdUtOcm0KCQlCb0pOSWNGWXcyZGdsN2lpcmkrRWxZeHRkZUJw
	bWM4YTg3d1lTSFZVWTZURGNmSVQ1dnFDc2U3RHhyREgKCQkwVEV2VytVMVFZNlBCZGMz
	KzMyb0Mvek03ODBlUXIrWjBGYXAzVHlXay83OWd4NExmWWRCMUFrUU16b1EKCQlnRGpa
	anhwWVVWbEZDcnNUQ3VzdmpyQnpqNzVqWGczMEV3bzlZVFZPV1VycGhKUE14MHdhd1pO
	T010Q1EKCQlLTVRaWW53eHJrTlI5a0xrWG1XaTFNMEhzT3pza0tXdFBRWXA3SmdKQUlP
	NGZQc2d2SGZrTEg1djZWTksKCQlLRW9SalhDWFpFdEt3dG9hRW85NjhPdWV5SXE5SGJ2
	RktXT3hvZkhyTWlHK0Z6UWdsQ1l4dVVBZVg5MHAKCQlNeXRwdE5oUDZGL3o3UkZHWU41
	b0N2M0lLeTMzcnkvQmtNUks0OEFiQXM5cDJwV2l4Wm4wVVJnZzErejMKCQlxVEp0eWlG
	eXgwVGFLUHlqWDgvWm9adnhxcG4xTmpGVFhhQjB6cjhEUHJkSXV3NVNHRGplcFB5OFRW
	V1MKCQk4d3BvdW5vTDZNd1dqQm1ndEZia05PNUpVcGJMamdZOEh5MWFjRDhRNGU0Yy91
	ek5XNHo3YVVRMWJxZjgKCQk5blFqNXg2a1R6M0YyREVPc1ZaV2ovL1ZCSU9LeXRkckJr
	cFMyY0dKK2NRNEcrbmFIdEIvNEEzdjRBeHIKCQlZSUx6NUgxZWJvcVZSUXVXeUhvUE91
	NGp4bjZRU0J3UWVCQmp0M2oyQkJpVjJlWi84OGpWcis1WXQwS00KCQllT2JUWmJpSHM1
	c1hQN2JXR2JBRGN2TUFTaXlWUTZhS0M5VUZHbWNnZXBvYWs5Wkc0MFZBVjkxU0srUEUK
	CQlNcFcyakpmaS8xMHBHM1VrUXQ5WkZkd05jeTVLMTh1aU1UVkQ4SUNUQWNXdmJ5blN6
	Z2VpNFhseVJuK24KCQlTTHJnNmJIbG4yc3BjT0RiRnpWRG8zaCtpcHhLbnR2dzNKeFNM
	aFRRUTRHNnFrSFNrNmNjTjdTNEZjWUUKCQlsNXluV2FuL2F4ZVdDTCtxdWZYYjRwZHZL
	b0hNWEdCcUxUVDV6ekg2bHcrNHRRbkptSjZWcWFyN0lTVlUKCQl6VjA5ZUU5ZW14cDRH
	RzZISHBxbXhweDJHS2pTSTd2Tm5adXFXaDVHcnR1K2x3V3BXQjJWOVZJMWoxYXAKCQlC
	ei9La3l2US9yeGRNNklnZktkNXFUK1NhR21EMjV3Ym5STm5Hcmp5WnRRS0U2OVpRZUtG
	akExUlpKeXEKCQljSEY3Ly9MMm85UFlXZUdmMFh3VUpqWm9jSXNBcFZVY3pFUm5kSExM
	SmZDK3kzL0x6YnhvK3JwZ25JZ2EKCQlXVEljb1UvNXpOMXBzU3NtZDQ2MnpuMFNzRndD
	VWVwdVRESElKbUpPTjVLRUZLY1hwN2hwYWs1NXFZVXkKCQlJQStnUUl5dWk0Q1JxTFdI
	SVBVK0FydzZwVTF3LzNINlh2ckRmNm9hbTBZQkpiUGRkQVRTWktWcHczQ0UKCQlWekMw
	eSs3WVgyZFBsN1loSVRDemRmNENHMkJEOVFhMFdCTmV2Y2Fqak13REgvYnhIdTVIZ3pi
	N053RTAKCQlnamdMSjZuaFF4Qk1QYmJqYlViYUM3UXFXVFpwUFYwSzhVdzZ5QmNPQTh3
	SzJaZzlmOTJaeW4xQ0JtMSsKCQlpeHBLTHVkenUxOE52OUZ1TUJBaThQTE1Qd0VmYUtV
	SUdvQSs1RjcwdW5VVmRGK1FubGROM090c0RoUXgKCQlMTHk2bUNKOWNrWlYzR01saHh1
	Si9RdC9uaUpLLzdQREpuMzRaV05DYjdhRFdUNmgxdjFOSEdrZGlsd2gKCQk1V0VkL081
	Q3MydmJ0blpRT1hFRzBJd05iL293b05OVHdOZkRpUk1nSWs3RVRUcmxHSG5uZmNGT3R6
	RFkKCQkxYk1KRmtMRUwrOUNOaWlXWG1oVDEva3FxVnBodnBIcTRINXdPK00ySzl5c1dS
	WmR3N0pkS3lzcVgyL04KCQlaQ242YnUzdDRyTnhWcW5rRHJzNU9pL0VzZEd1bDBFZk5w
	NUhLV2djMEZzYm4rQXNaUDVsUGZ6OTZwODQKCQkvYkZuTzFYMFVmMnJ6U1d1V1JUdlhP
	dWJLSSs0UVVmTUtkVVVkMXhHeUh1bUJRZTU1bHNaUW1tdE9GR08KCQlzaWVCRkwwL1pr
	Snk2S0EvVGU1cDRiWTdnV21KZ2FJU3pNeXY3VHd6QWI4czFCOWo1VUE0TTRGRXlESW0K
	CQlMTFZqV3JyUUthamtFTVI1Y1V1UTJiU3IxZGpyS09RQUEyOEJyY1pYcW83Z2ZiY1pJ
	bWRXa0tGV3djb28KCQlhaXVZcnUralRzdFlJOGFSdDA3WUNJZnh1UUdpOEF5dWZpTUJY
	SWNraVNwNk5jRmw2LzZqTWFDTUNESGoKCQliYlBUYkV0TzdpZEI2anBOY3E3VGVmQXNV
	bThsMlZ2V3JEZGJoSUpyengwRzNCbWt6MU1nb09FL1ErSEUKCQlMYUhNUVdpTzFmWTdX
	dzFtT1JZVnJkVlZnTEpHSVRRM0RMS3laMVg4UzJoRlpaeTQrUGlDY3dzbUZZQWMKCQk5
	NTc3SDNjVllic3hwdnVPQVNLdHNkM1ZHWEhnT21aaWd4RmZacWtTQm9nVTRmaURoQStq
	b0Q0eTZvQjkKCQkwK2IwNml4RDlaL2NXQ1VMNHlUTGRmbDJhQ0ZDbk1QT294QTMrUkV2
	SmVRdlNTMlBQQzdLMURQTGpyazIKCQlhdWhHQ1BTb0oyWDhJM1RPcTRSY21oSnZrajNP
	Mm5tWktZUUxWdE5lZE1pYmw1eHB5U0ZueEIrNTN4RjAKCQlET3JRQ3VJMXBrZ3krUXl4
	UEtEYnB4TzhaWTNZOGdUekFnNTY0cFFUZUhvVnArZXNFUDJvd00vcndqemkKCQlCSHdN
	bHVaZkMyODRVZzU3TTNSeUhCYWpuNFBYSFFnbXVJT2p3VUhjNDh3MG1WanA4NTJHZENm
	NVZyMngKCQkwek5DYXN2V0VCYWp4a1AxdnFZZGJNL2c0aVBHYU1LVU9uUHRmbEJUdWxS
	eXdjMXoyZC8xUE11Sm5UNUgKCQlGTDFpTkJ6UHg1VU1pU240TFhMK0JMMUhJNGNxTlNF
	MENHK3I3VWY1OG5FZnB4b25tdi8vTVlIanFxMVEKCQliQWwwVzlRaUQ5OUtPKzJhV09E
	NGdVby8wUjF2amJDQ05yN3N6d2RhNnNXdmxyMStnYlNaUWlNRUgwUHQKCQlnSGRXaG5P
	TTQ5NDRJei9KVnk2TFpWRGFvWFpXNW5ocllSaG9vZzhuRWRvWWNsdzZKOU5KQjZzTm1o
	bWUKCQlXTTZTU3FBTmR6d2RjYTNsaXBuNTdSUW5mUmsrOGdpM2poR0VjSE4vb3JpTmp6
	ZjVVNzY4VkprSVVVTisKCQlJMFhTME12NFhvK3piclhtSlU0K0Q3RktiREx3Z0NOQWd6
	ODBVU2NYU05UWFNyZzhuZzZIVkUwZnRDdHAKCQl4bFMybmtaR0wvWVRYaStCWU1UZ2Vl
	UUgxdmFKeTNUQ2lHdXJ4aW1LeEVWNGxhTUdFRjdIdkZ4dDZXOW0KCQlFN2NmakZYaFZt
	Qk5qWndyTnBXZk45N0pTN0o2ZER5N0UrRDF5ZXlUN1U4WWZVcVp3M2VMaFRPbTR4Qk0K
	CQlyaFJlZnNOWGNldVZDeTUyUS9YUXBhWDg2cy96a0s2ejJaOExnTEFZa2RLcm1CUmIz
	NldOQWNSejNsVE4KCQlVQnVQdEZTU2hZdFhYdjRWVmthcU1jWGFxWFpFMG9qMWU1QTNK
	SG9SWW1oeHVkbjByTVRtWk44UkpaMXAKCQlyTUZiUVRkMEJ2SWZvLzd6cUJFd3ZVNC9I
	bUMrcUZiVWRwMW5jbFZ1V0l2RU1WbzJMbmtzWXA3QW1JWGsKCQkxQlFiZHN3aXo5US96
	S3RnSXJsUzdQemo5Qk02em5aRkp5akpwNGMyK3FBLzZPMUplbklqVWMrNm5KbXkKCQlS
	ZnFZZzM4Q3hXL2JuY29pRXR5czhYamtwVHFxNGQzcUhad25YbzNtQ1BDc3poUTFPclJw
	UEVBZ0hmS1cKCQlZV3VjWTNqUEpUMERLYmZuM1dVRFlXUW5vd1NnYVNRNCtTaGkvbklu
	M2JUR3pUQUlrZ1lFVXpKUlNMc2EKCQl1aHdkYnA0cXRtekZNdWZ3THVpOTlyRTNNR3NZ
	VFJYeTQ2bjRYRUNnV2VJbFhXTDBGVXIrSEpwQ3JlaC8KCQlua09xaWk2UGhVdmlSc1Fr
	eEFTblpvcWprZjlibjBYMGpBbU5VYnpyOWYzM0t1THFHT3IyYUZ4SWVzQkkKCQlHWlY4
	aldHMzJVQ05tQ3NhSlltRnBXellCN3ZKSk54RkFoVVgrVmZGaGFCV3VqbnR2YUNXam04
	anI5UGQKCQlVNElqczF2aUV2UEtyWHprSVJqN0tDMVV5QityU3FUNWhrNEJBanBOSmNo
	RGtxdkcwdlpOLzhmVi9RczQKCQlXZXBKUmoyNVJSbVRaaHhoQy9FOUJBMmJ0UEpYOVN4
	RzRZTnhib1N4OUgwVllWUjhPSUxSVU45Ylh4OFgKCQlqRWRTNWMyTW1xNldMQXFGWWcw
	bi9hV3JKUmRWS2RqZlFGcWJ4SmcyalpQTmlMMll3OTUvZFhFbCtTN1kKCQlzZmUwSUV6
	SU9rWVpKNDgxSHBLNUQvMDcyTXpaVlVOV2tnMkJxbUtoZEhmVHdwRFo3TlJHUXY1K1ZU
	YXoKCQlkTjhlcWhRSVZvSlc3UGJFSTBNNFVjTWpuZm9MWDFsYVFLOXVVcHk2TEc2Vjds
	K0ZBaFFwZDhyT1d1UzkKCQlhWm9rSU01ZGNoNTNQVEhuM1dQUTNhd2ovbFRoeTE0TGk1
	OVBvVWoxcnRQY0duTnNWZUJTWXl2Uk9pZTMKCQlMVGFuTnVtZDNBRFM0bkFsSDJwOW1H
	V1huQ2NqUGdCQUlQYWpnK3NpWUtCN0N2NzluK2w2b2FpczQrdHkKCQlBZkZsVUNJYWI3
	YjQzbklqbmNZQk8vSmxrTWFiMzh4RDVQUjlVYUtqaEI1WXRpTTdPY0FoaSsvVXFlOXEK
	CQlURTVIdTZ6d2lUZS9XZ1JkQ3RZVkJUQytFeE5Bckd3K29ldXJWWlZvL0tUTzJGVTYz
	WjVnMTZZTjVRK1gKCQkrZWgrakJlYkU1ZVF6MFpYcHdSOEtKT004Nm1PbXUvSnI1VTls
	T2lFdmIzWTVnSDNTS1ltRWlxQUszUlMKCQlHbGFWd2ZVN09URXdMU2pzVGNqa3M0eGtl
	VktHMFdlRmMyUDNOdkpVR1BSbit3ZTBtbEVoVHBEQk1LdUMKCQlIYWlTRVlqNFJhN1Fs
	UTVUaTQ2OVVlZ092VkcyY0FmaUVWR3gwZXFKL0g0eEx2WDl0MzB4WUpXOW5PYUUKCQlh
	R3doZytDeDRmNjJtRE9WSTFkcDV0NEZXSWttRThmQlc0cWg3bWJnMWdOUGpkNWdIcmph
	YzdQNHl5R04KCQlBaVJjTTJma29YZktqWkR6NUhqM3AwdTUxVXAxMTVvZ2lxMi9iY1lQ
	VVV0cExEdDNPZ2UvRXFNTXF4QW8KCQlUbVVHKzNrSDZucFNuN2JTWkFEd3FKVjZJRjNZ
	TVN3UmtZTW1QUHc4eXpZbUtlYkZRODQ1ajZ3bFlyazYKCQl6UWV0R3UwZjlpckQ2Wng0
	K0paaGdiLy9UaVpZLy9ua016QWJmbCtYVUIva2ZSMW8vMy9aa2NVTi8veUwKCQlkeG9N
	MjVtWk5xKzNZajhMSnhrbTc1NGc0WTV3eUhYUFlmZGNNRGZQMm5ldjZtK0twN1NkS2Zw
	STlhUlkKCQlua2NXL1lIYmw1ZXVYZzRBeUlpVDdTZGFXcVliV0pWTytwSFdUbkZLV2Fi
	SXBOTUVCc2Y0ME1zZWp6VGsKCQlwYzZFQTFhdENCUG5NMzl3RWRDTWZ5aUg1ZVBROTZH
	Yk9Sc2V3U3cxSVY0N3RkUFd3aU8vRUgwMitHVHEKCQlSZ2F4dkR3NFNrdVJQK2ovdHpm
	S0ljYkozY0RkUmVHbVRuc0NNazI5RjEwazNCT0dabnJBS1duRFVVbk8KCQlIL1pVT2J0
	dEtSK0lZbUhteHJVY0hIYWdBcnhrODRzbmEvUzFURTd2NDFVbGVsVjdXS3lUMC9Pby9Y
	MDEKCQk5KzlIbmM2dFhEK1phNWxLUGx2aTdvN3JoWFI5aVJxM1VFRmNpL0kvcG9YbGRP
	N0thQkFtZSs5ckZIWTkKCQlIdnpSQXNjVlF5aVdMQTNUeC93RWRMcE9vblRyU1ZWRUNV
	MFBMMXFaWmgySFNGRC9kNER0cVljNW1UWWsKCQlabGQ5OWFHZThFKzhTUDZ4YndsYTJC
	TlAzS2RHVzljdGpMaUViYlZxMzYzSSt6NzJJaHkxTTI0cWF0eDkKCQlVRGJZN053TUN6
	MXQwWmJoNldOcERYSlhCVWUyL0xHdHVud3p5VnhpdHFaMzhPRm9sOGVwTm5wMWcyQmsK
	CQluU2V6VXpsRXAzZ2kvK0lIandIMEE3dUc4ZGJHbUlCWlY4RTUwSk5USlNJc3pnNVhK
	R3BPbnpXMUhqcXAKCQk3WTlia2xvWDlmM0tqUFc0K0dHWDFVeHVQQTJ6bzgwbDl5ZGd3
	SGRmZkgvQjFaVzZPZ1dFbS92bElPa2QKCQlQcjNsOERxRjFCNUxnOEZHeHd1RE56RDhu
	QUMxSWxUSTdOUWNNMUVnaHhjdVFObWRJQjdOYnVoM28rb2gKCQlXNjRhaldKVkl5Tm43
	blRDVlR0cExWVTJNM2JPYUwyN04ybW5vYWR2U0pxZmZ5SE9PQWdVWnVLZXlUT2IKCQly
	eWZWSzFzSVpodlB5S0tmTys2akVZYXdFcERINkdvaGhzMm5GSjMwMWpTcDRWQUJsMWRk
	RkVWbXVPZEwKCQltY24yOVE2M21UekVyZ21ucjU0YllDSkVaemltN0FGT01ZMTgvQkov
	NlNibXpYWUVsYmVwR3I1RFhJR1kKCQlIN1YrSUdxQ2JRRmFXYWR2Ky9IUFZmZG9yVXc0
	NkdudmduZE96VGRJbzlUWDBIaDgvWFgzd1Bzblg2QysKCQk4L1BxclN1ZDFGZFFWdGla
	TlhPSVN1Z3FTdkZNWHJnMmNuQ1Q1d1hZTll3a0xSUHZWeDBvWE1RZFpYM1QKCQlZRnBU
	WGl3RU12VXdidExYVk1UVEtGSHhLLy91N2hFUU5iYWFMRVdxTDRwSnhVUlEwUmJNM2VO
	M2tDZU4KCQlWS1NqV1J5Z0tPOGRNNS9SeDJUcDJrdndWdTB3ZlNGMEJCSGhROWI1K0Yv
	STJndnQwTVhuVDd2SUs4SVUKCQkwSzJVNi9UQkxWQXk1K2h1c05GTStKVkN0MDZPNXc1
	VUk1YmhMZU1xdGxCK2xvZVpPZ1R0RVhqNWI0TEMKCQlWUmpubURkTGY0RzRRMnJUcHZt
	cGJMRT0KCQk8L2RhdGE+CgkJPGtleT5XaWZpQWRkcmVzczwva2V5PgoJCTxzdHJpbmc+
	YzA6ZDA6MTI6YjU6MmI6ODY8L3N0cmluZz4KCTwvZGljdD4KPC9kaWN0Pgo8L3BsaXN0
	Pgo=
	</data>
	<key>FairPlayCertChain</key>
	<data>
	MIICxDCCAi2gAwIBAgINMzOvBwQCrwACrwAACDANBgkqhkiG9w0BAQUFADB7MQswCQYD
	VQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlm
	aWNhdGlvbiBBdXRob3JpdHkxLzAtBgNVBAMTJkFwcGxlIEZhaXJQbGF5IENlcnRpZmlj
	YXRpb24gQXV0aG9yaXR5MB4XDTA3MDQwMjE1MTczMFoXDTEyMDMzMTE1MTczMFowZzEL
	MAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xFzAVBgNVBAsTDkFwcGxlIEZh
	aXJQbGF5MSowKAYDVQQDEyFpUGhvbmUuMzMzM0FGMDcwNDAyQUYwMDAyQUYwMDAwMDgw
	gZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMItpElXR5LEZHl6nampVJ2vK52FNvWV
	UPzB7fpEA1nlsbZnJbhvYMWy1g9jF4F39irxEDGVTcXWbihhpXSnlclysQdZ4/DcbDJK
	PsyGdo9aMMPbdy91dpIxTxZs66XJZfTA9jhYRWih22cLAQzWwe/urS6NvDzAjgUUyoBI
	7e8tAgMBAAGjYDBeMA4GA1UdDwEB/wQEAwIDuDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
	BBT8e3f9V3tlTvFCvTFB33VOBj2JsjAfBgNVHSMEGDAWgBT6DdQRkRvmsk4eBkmUEd1j
	YgdZZDANBgkqhkiG9w0BAQUFAAOBgQAu4A+hdIB002KcTdaFvkXSHKk/WsLc/AvEC0hT
	Ixl2zyC12xx/fJRrL/4LF0Yu47rszTfBtbFDlWeLTN3mED+/3XaiCPFNAZp3oReuljcY
	6BmoaHViaJ9Ql0Q0VK3gAfbJyghKY1JE1fzLQIf2CKdF7q2cUMnyoVxixck9RMUBzjCC
	A3EwggJZoAMCAQICAREwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNV
	BAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9y
	aXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTA3MDIxNDE5MjA0MVoXDTEyMDIx
	NDE5MjA0MVowezELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNV
	BAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MS8wLQYDVQQDEyZBcHBsZSBG
	YWlyUGxheSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCBnzANBgkqhkiG9w0BAQEFAAOB
	jQAwgYkCgYEAsmc8XSrnj/J3z+8xvNEE/eqf0IYpkAqj/2RK72n0CrnvxMRjyjotIT1S
	jCOJKarbF9zLKMRpzXIkwhDB9HgdMRbF5uoZHSozvoCr3BFIBiofDmGBzXmaXRL0hJDI
	fPZ4m1L4+vGIbhBy+F3LiOy2VRSXpE0LwU8nZ5mmpLPX2q0CAwEAAaOBnDCBmTAOBgNV
	HQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU+g3UEZEb5rJOHgZJ
	lBHdY2IHWWQwHwYDVR0jBBgwFoAUK9BpR5R2Cf70a40uQKb3R01/CF4wNgYDVR0fBC8w
	LTAroCmgJ4YlaHR0cDovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS9yb290LmNybDANBgkq
	hkiG9w0BAQUFAAOCAQEAwKBz+B3qHNHNxYZ1pLvrQMVqLQz+W/xuwVvXSH1AqWEtSzdw
	OO8GkUuvEcIfle6IM29fcur21Xa1V1hx8D4Qw9Uuuy+mOnPCMmUKVgQWGZhNC3ht0KN0
	ZJhU9KfXHaL/KsN5ALKZ5+e71Qai60kzaWdBAZmtaLDTevSV4P0kiCoQ56No/617+tm6
	8aV/ypOizgM3A2aFkwUbMfZ1gpMv0/DaOTc9X/66zZpwwAaLIu6pzgRuJGk7FlKlwPLA
	rkNwhLshkUPLu7fqW7qT4Ld3ie9NVgQzXc5cWTGn1ztFVhHNrsubDqDP3JOoysVYeAAF
	2Zmr1l6H6pJzNFSjkxikgzCCBLswggOjoAMCAQICAQIwDQYJKoZIhvcNAQEFBQAwYjEL
	MAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENl
	cnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTA2
	MDQyNTIxNDAzNloXDTM1MDIwOTIxNDAzNlowYjELMAkGA1UEBhMCVVMxEzARBgNVBAoT
	CkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5
	MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
	CgKCAQEA5JGpCR+R2x5HUOsF7V55hC3rNqJXTFXsixmJ3vlLbPUHqyIwAugYPvhQCdN/
	QaiY+dHKZpwkaxHQo7vkGyrDH5WeegykR4tb1BY3M8vED03OFGnRyRly9V0O1X9fm/Il
	A7pVj01dDfFkNSMVSxVZHbOU9/acns9QusFYUGePCLQg98usLCBvcLY/ATCMt0PPD509
	8ytJKBrI/s61uQ7ZXhzWyz21Oq30Dw4AkguxIRYudNU8DdtiFqujcZJHU1XBry9Bs/j7
	43DN5qNMRX4fTGtQlkGJxHRiCxCDQYczioGxMFjsWgQyjGizjx3eZXP/Z15lvEnYdp8z
	FGWhd5TJLQIDAQABo4IBejCCAXYwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMB
	Af8wHQYDVR0OBBYEFCvQaUeUdgn+9GuNLkCm90dNfwheMB8GA1UdIwQYMBaAFCvQaUeU
	dgn+9GuNLkCm90dNfwheMIIBEQYDVR0gBIIBCDCCAQQwggEABgkqhkiG92NkBQEwgfIw
	KgYIKwYBBQUHAgEWHmh0dHBzOi8vd3d3LmFwcGxlLmNvbS9hcHBsZWNhLzCBwwYIKwYB
	BQUHAgIwgbYagbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0
	eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFy
	ZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBh
	bmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjANBgkqhkiG9w0BAQUF
	AAOCAQEAXDaZTC14t+2Mm9zzd5vydtJ3ME/BH4WDhRuZPUc38qmbQI4s1LGQEti+9HOb
	7tJkD8t5TzTYoj75eP9ryAfsfTmDi1Mg0zjEsb+aTwpr/yv8WacFCXwXQFYRHnTTt4sj
	O0ej1W8k4uvRt3DfD0XhJ8rxbXjt57UXF6jcfiI1yiXV2Q/Wa9SiJCMR96Gsj3OBYMYb
	WwkvkrL4REjwYDieFfU9JmcgijNq9w2Cz97roy/5U2pbZMBjM3f3OgcsVuvaDyEO2rpz
	GU+12TZ/wYdV2aeZuTJC+9jVcZ5+oVK3G72TQiQSKscPHbZNnF5jyEuAF1CqitXa5PzQ
	CQc3sHV1IQ==
	</data>
	<key>FairPlaySignature</key>
	<data>
	iDInLWMRGOQU0M5MddENIwD+9q6cq493YZlM8WALoig/P+dVVo0yCmpYt6+8UKEyWGx9
	zV6JRaKUHcqPc4M8rFKvbT8yiBxFWf8FreOknxG3ZwFVTTMC7xpQFbFhl2luwiZCAeCw
	eO4JRvUUUTefrG5NOnjDOYCpfkR+ucfwBAg=
	</data>
	<key>RKCertification</key>
	<data>
	MIIEPgIBAjCCBDcEIP4C3sqQtP1S2hwBZzCoHcsoH2xNu5c+a4Q45oJ1MKF3BEEE29TZ
	UxnJF5YCE1DRQ8gcwonvUR+OUnqC+Zof7u8xmdJ4H8qwSm3twGZbfODpkIhAdvUMnQPl
	sSGxxviT9t6hywQQWgUYXmlU5RqzqVq5iuI4pQQQSrIhzuDP4FOjCX3Ixf9KRASCA6qC
	YDMeIbIxtqI0BUNqxuSCXJ2dNRMmG8HyfjU9BuvhMevykmE/YFDMo+8GM3WZk1GsvHPk
	iAHq0EzBOKMHDhz0tdQCr43OJpah1wsL4rQmsxB8dnRigoGjA5d3FX8A3c2Vp56wTO7F
	0ouu+U1Lh8PUADaqMA9sFvFdC6YQk/788ey66s3tobIFARBPfj3SonYIu48i1II7tLwO
	6eaUq30Bl3KseSTFRerYYCK5GmUAXZNSIwVxc6MSAV6H9VDzQVW3jjzCgof/kRzlfHap
	zwokiDdG2hN0zCUJqkkUpOD9uXsyMr06oz9MVGemaWuZD/RYoqx3QmUha1+69EUZFuUw
	P0oJdHE20iNspn/yBQSNMRT72uieMR5PVoj/OmdBhCpzaqQDI/LD4m3oVh5zqTBLHE38
	hHerP8dPkztaJj3+tspKVWQOQMGwCwNDaDnN2Z3jy8zm/P3XLYLHExxbNNhCxTLQyB5Z
	zmHfMPhySTtVBBlJseglcZCDo9CfS2TIHU4Xqz9il/Qgjjsn9UA0HWOArghScs15b58j
	K7r6uge1mAtzOPiTJ0pSVv4yxuw8QCZIwCdfOomZtO9W1bEFPjc0cxQcIueSosRhmTf1
	zrrAsXnUJC7k2zfCIE+2RJIyMXnvGjI9kfcyvi1PlUMMKU6fl+yYXS9vj38KMYcVVPyI
	QgSeGIBCycJBlA3BaUXYJ2mtYadbJTFbEptigcAhXFfmb2YdpNB69SzCKKolDul9q3PQ
	IX70igLd120dDkT3VtuB+YHhjYJuXHKW8TgOCJekm79vQW8ksXvtOnVYn/BWIp9VcHyc
	7m929r2058eBV+kgLHBb8uHkLcBfJ3Kew0yigODzGWMusgmjaH0l6NLWjshgMsY/YLoH
	EauD0i4xXY7U28euqskzzP7lO9iGfF/reWxsD1Hq5q5uJEHLgUpU26H5y165RFeGBRbR
	2gJIVIKv0/ENTK3WmbKwbL/h7GTQJ47+ObiNhgvpOtEY6qIbtB2Oym+9TlIBqviBXNEY
	MbLN0qx46VfLe4kT5MMy4W7qAS1+lhLcAoPvTEuemtkg0teR5gGVVCzyLk+1tAclRIlF
	MvucqZPr+dC/UwuVKJ7T/whY3u5f9ck5X4pNpefqwwkb1VdWapj91qMR0NsOLPR0rjw5
	iUjyFIYrJ6JMHSQIqQbvn4O+0LVg7trpmCes3St9hYcaR8Rms7UfVJ72F860CfXEQ5dm
	vRcXqGpLJZ2xnuNTyx8/kUAO6w==
	</data>
	<key>RKSignature</key>
	<data>
	MEQCIArGkUPVunLKOWmwYmlmDtoapqLS1+6ESVhlZ50E4LfnAiAZg+O+94Od4DUOY/R3
	AJ0pcuhD0AdArNfYSd7o24/XLA==
	</data>
	<key>serverKP</key>
	<data>
	A+zlI0AqXTa/fEIKYPC6FrMdohCdQmQvd7V2Dbhmz8lSF3PO9SKdScUvYjjx50lRHJCf
	BDFuSLhb7ewZWowz4TvOQL69
	</data>
	<key>signActRequest</key>
	<data>
	ZltPZT7sEaXhbn/NLGwuRQ==
	</data>
</dict>'),
    CURLOPT_HTTPHEADER => array(
        "User-Agent: iOS Device Activator (MobileActivation-20 built on Jan 15 2012 at 19:07:28)",
        "Expect: 100-continue"
    ),
));
$curlResponse = curl_exec($curl);
curl_close($curl);
//=======================================================================================================================================//

//Cargar la respuesta de curl a variable 

$encodedAlbertResponse = new DOMDocument;
$encodedAlbertResponse->loadXML($curlResponse);

//Imprimir respuesta de curl

$decodedAlbertResponse = base64_decode($encodedAlbertResponse->getElementsByTagName('data')->item(0)->nodeValue);
$FairPlayKeyData = $encodedAlbertResponse->getElementsByTagName('data')->item(2)->nodeValue; //OK
$deviceCertificate = $encodedAlbertResponse->getElementsByTagName('data')->item(1)->nodeValue; //OK
$accountTokenCertificate = $encodedAlbertResponse->getElementsByTagName('data')->item(0)->nodeValue;

//sacar el tiket del wildcard
$accountTokenDecodedAlbert = base64_decode($encodedAlbertResponse->getElementsByTagName('data')->item(3)->nodeValue);
$WildcardTicket = explode('"WildcardTicket" = "', $accountTokenDecodedAlbert)[1];
$WildcardTicket5 = explode('";', $WildcardTicket)[0];

$FPKD = $FairPlayKeyData;

$accountToken=
'{'.
	(isset($imei) ? "\n\t".'"InternationalMobileEquipmentIdentity" = "'.$imei.'";' : '').
	"\n\t".'"ActivityURL" = "https://albert.apple.com/deviceservices/activity";'.
	"\n\t".'"SerialNumber" = "'.$serial.'";'.
	"\n\t".'"ProductType" = "'.$ProductType.'";'.
	(isset($meid) ? "\n\t".'"MobileEquipmentIdentifier" = "'.$meid.'";' : '').
	"\n\t".'"UniqueDeviceID" = "'.$uniqueDiviceID.'";'.
	"\n\t".'"ActivationRandomness" = "'.$activationRandomness.'";'.
	"\n\t".'"CertificateURL" = "https://albert.apple.com/deviceservices/certifyMe";'.
	($deviceType == "iPhone" ? "\n\t".'"PhoneNumberNotificationURL" = "https://albert.apple.com/deviceservices/phoneHome";' : '').
	"\n\t".'"WildcardTicket" = "'.$WildcardTicket5.'";'."".
	"\n".
'}';

$FactoryKey = 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJQ1hRSUJBQUtCZ1FDelltWHNTTjNkN1VUVThmNzd3bTlDMElJSkF3Q21BZWl4QndrbVd4SmwyMzlSRmU5UA0KUmJPUHprMFdIVGlFQVJCWFRveHg0VjdlWnhSMTJraWFURy93UldWbTZKeTFva3owVThIc21HS1FzSlMrRXZLZw0KckZ4M0ZnZHpjbHFYdWxCT1p6QlNIdkF3VG8reXBOUFIrdmhtZVllUkw2SHZUdVpCalpRWUtlRHl6d0lEQVFBQg0KQW9HQkFLTDd2ekZORDFDcFdJWEdEZTkrdklwUFdpYUg5Tm5nR0NSb0NSY3hYZWp2NHFDd3Rrc25RRHRqck1Sdg0KN2o1NW5QaEdaUEsvV3V2bGFrQ2VBS000MmVaRi9xMmdSQmVBWkpOUWtTSEJXOWQvT0V0N2JsYTkyRmorOElqUA0KQTNjUStleW8vS3lOdEY2T0w5S0U2Z2hNc2tLc0dCa2RNWmtESkhNeFZ1K3NLMzVwQWtFQTNRQmJPd0I0dFBkSw0KNHcrUnd1Zm9UbW1TRHhUR081dXZwc0JSbkZRNEswczNXZlBqaHVtRFFSQmVpYytIeFREWTcyTzEvaURwVGJMOQ0KcFRXNGY1cWVzd0pCQU0vSzEwOGEzNzBEeWJBODdGWVZ2TURPR0JKc3VkSXpMTGhOajRlUDRwTzIrRGFpOTU1WQ0KcVhURjFudGxPWDdsRDczUVlGeXJmcnZNcVdqNDNpM2xhWFVDUUZVeW12a1BBSG03VCtwakNTMWJXK3BHdHFFTA0Kd0RRZ204R3NLSW9jeVo2Zkc1S1kvQ0Q1aXJrZGgyU1hWZDhHS3N0MjVDVTVLTmZrWmZZMzFJMlUzUk1DUVFDNA0KRHFHSE5YUEgxb29ack8xZkYyUVptTFNqNVdEM3UxSzZjaUZYMy9EQURVdHlBZ3E2WFNqRkFkVUplbEZpZ0gzZw0KRWFxNWkwTDRFTUppOUViQmVydGRBa0FkTWVmNVNOa2dlMjZucTdueWxxMC9tVkEwc0VQVEEvYlNBTXJaRFZnVg0KNFVCTFhxMTJ5MXBRQXJKLzhyemtkTDR4NmZhazUwcXp1cEFhL0plcjhraWUNCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t';

$private=base64_decode($FactoryKey);

$pkeyid = openssl_pkey_get_private($private);

openssl_sign($accountToken, $signature, $pkeyid);

openssl_free_key($pkeyid);

$accountTokenBase64= base64_encode($accountToken);

$accountTokenSignature= base64_encode($signature);

// "¿" <key>RegulatoryInfo</key><data>eyJtYW51ZmFjdHVyaW5nRGF0ZSI6IjIwMTgtMDItMDFUMDE6MDc6NTZaIiwiZWxhYmVsIjp7ImJpcyI6eyJyZWd1bGF0b3J5IjoiUi00MTA5NDg5NyJ9fX0=</data> "?"

$activationrecord =
'<plist version="1.0">
<dict>
	<key>iphone-activation</key>
	<dict>
		<key>LDActivationVersion</key>
		<integer>2</integer>
		<key>activation-record</key>
		<dict>
			<key>AccountTokenCertificate</key>
			<data>'.$accountTokenCertificate.'</data>
			<key>DeviceCertificate</key>
			<data>'.$deviceCertificate.'</data>
			<key>FairPlayKeyData</key>
			<data>'.$FPKD.'</data>
			<key>AccountToken</key>
			<data>'.$accountTokenBase64.'</data>
			<key>AccountTokenSignature</key>
			<data>'.$accountTokenSignature.'</data>
			<key>unbrick</key>
			<true/>
		</dict>
		<key>show-settings</key>
		<true/>
	</dict>
</dict>
</plist>';
header('Content-Type: application/xml');
header('ARS: S3ReFz/yLSkuM33VbNhgsw==');
header('Cache-Control: private, no-cache, no-store, must-revalidate, max-age=0');
header('Content-Length: '.strlen($activationrecord));
echo $activationrecord;
file_put_contents(''.$folder.'activity.plist',$activationrecord);
die();
?>
